version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: asam
      POSTGRES_PASSWORD: asam
      POSTGRES_DB: url_gami_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://asam:asam@postgres:5432/url_gami_db
      NODE_ENV: development
    command: npm run dev

volumes:
  postgres-data:
